import type { AppProps } from "next/app"
import Footer from "@/components/Footer"
import Header from "@/components/Header"
import "@/styles/global.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Header />
      <main>
        <Component {...pageProps} />
      </main>
      <Footer />
    </>
  )
}
